# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: marketdata.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'marketdata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10marketdata.proto\"l\n\x0c\x46\x65\x65\x64Response\x12\'\n\x05\x66\x65\x65\x64s\x18\x01 \x03(\x0b\x32\x18.FeedResponse.FeedsEntry\x1a\x33\n\nFeedsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\x05value\x18\x02 \x01(\x0b\x32\x05.Feed:\x02\x38\x01\">\n\x04\x46\x65\x65\x64\x12\x13\n\x04ltpc\x18\x01 \x01(\x0b\x32\x05.LTPC\x12!\n\x0bmarketLevel\x18\x02 \x01(\x0b\x32\x0c.MarketLevel\"-\n\x04LTPC\x12\x0b\n\x03ltp\x18\x01 \x01(\x01\x12\x0b\n\x03ltt\x18\x02 \x01(\x03\x12\x0b\n\x03ltq\x18\x03 \x01(\x03\")\n\x0bMarketLevel\x12\n\n\x02oi\x18\x01 \x01(\x03\x12\x0e\n\x06volume\x18\x02 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'marketdata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEEDRESPONSE_FEEDSENTRY']._loaded_options = None
  _globals['_FEEDRESPONSE_FEEDSENTRY']._serialized_options = b'8\001'
  _globals['_FEEDRESPONSE']._serialized_start=20
  _globals['_FEEDRESPONSE']._serialized_end=128
  _globals['_FEEDRESPONSE_FEEDSENTRY']._serialized_start=77
  _globals['_FEEDRESPONSE_FEEDSENTRY']._serialized_end=128
  _globals['_FEED']._serialized_start=130
  _globals['_FEED']._serialized_end=192
  _globals['_LTPC']._serialized_start=194
  _globals['_LTPC']._serialized_end=239
  _globals['_MARKETLEVEL']._serialized_start=241
  _globals['_MARKETLEVEL']._serialized_end=282
# @@protoc_insertion_point(module_scope)
